Use multiple build jobs (Build/Test) for performance (#122)

diff --git a/.github/workflows/build-main.yml b/.github/workflows/build-main.yml
--- a/.github/workflows/build-main.yml
+++ b/.github/workflows/build-main.yml
@@ -23,12 +23,27 @@ jobs:
         run: yarn install
       - name: build
         run: yarn
+  test:
+    runs-on: ubuntu-latest
+    env:
+      YARN_CACHE_FOLDER: ./.yarn/cache
+    steps:
+      - uses: actions/checkout@v2
+        with:
+          ref: ${{ github.head_ref }}
+          fetch-depth: 0
+      - uses: actions/setup-node@v2
+        with:
+          node-version: "16"
+          cache: "yarn"
+      - name: install
+        run: yarn install
       - name: copy env file
         run: cp .example.env .env
       - name: setup test db
         run: docker compose up -d mongo
       - name: test
-        run: yarn test --coverage
+        run: yarn test --detectOpenHandles --coverage || echo "Possible test failure, attempting to upload coverage anyway"
         env:
           # Current max memory size of Linux hosted runner is 7 GB
           # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
